name: Build deb or rpm packages

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ main ]
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y debhelper
      - name: Build
        run: |
          make deb
          mkdir upload
          mv kubescape_*.dsc upload
          mv kubescape_*.tar.xz upload
          mv kubescape_*.deb upload
      - name: Upload Debian Package Files to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubescape_debian
          path: upload/*
  rpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ matrix.platform }}-go-${{ hashFiles('**/*.spec') }}
          restore-keys: ${{ matrix.platform }}-go-
      - name: Start packaging environment in container
        run: |
          sudo apt-get install -y binfmt-support qemu-user-static
          sudo docker run --platform linux/${{ matrix.platform }} -v ${PWD}:/work -w /work -d --name rpmbuild fedora sleep 21600
          sudo docker exec rpmbuild dnf update -y
          sudo docker exec rpmbuild dnf install golang cmake rpmdevtools -y
      - name: Build
        run: sudo docker exec rpmbuild make rpm PWD=/work
      - name: Upload RPM Package File to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubescape_rpm_${{ matrix.platform }}
          path: rpmbuild/RPMS/*
